site_name: Hume Python SDK
site_url: https://humeai.github.io/hume-python-sdk

repo_name: HumeAI/hume-python-sdk
repo_url: https://github.com/HumeAI/hume-python-sdk

theme:
  name: material
  font:
    text: Poppins
  logo: assets/favicon-hume.ico
  favicon: assets/favicon-hume.ico

extra_css:
  - stylesheets/extra.css

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/solid/house
      link: https://hume.ai/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/hume__ai
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/hume-ai/
    - icon: fontawesome/brands/github
      link: https://github.com/humeAI

plugins:
  - search
  - mkdocstrings
  - mike

nav:
  - "Home": index.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
